version: '3'

services:
  web:
    build: .
    command: gunicorn project.wsgi:application
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - ./:/usr/src/app/
      
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
volumes:
  static_volume:
  media_volume: